#!/bin/bash
# Regenerate Claude Code's agent files from AGENTS.md on session start.
#
# AGENTS.md is the source of truth for agent instructions; CLAUDE.md and
# .claude/skills/ are generated by ./sync-agents and are gitignored. A fresh
# clone or an ephemeral remote container (Claude Code on the web) therefore
# starts without them, so Claude would otherwise miss the repo's instructions.
# This hook closes that gap. ./sync-agents is incremental and idempotent, and
# needs only Ruby + git (both present on the Linux web containers).
set -euo pipefail

cd "${CLAUDE_PROJECT_DIR:-.}"

if ! command -v ruby >/dev/null 2>&1; then
  echo "session-start: ruby not found; skipping ./sync-agents" >&2
  exit 0
fi

./sync-agents
