import CreditKit
import Foundation

/// The Where app's attribution report, read back out of the bundle it ships in.
///
/// The report is generated by `./attribution` and committed into the app
/// target's resources, so — exactly like the commit `BuildInfo` reads — **only
/// the app target carries one**. A bundle that never received it (the
/// RegionViewer developer tool, `StuffTestHost`, an app extension) reports `nil`
/// rather than a placeholder, and the About screen says attribution is
/// unavailable instead of rendering empty sections that read as "nothing to
/// credit".
///
/// That distinction is the whole reason this sits above `CreditKit`: absent is a
/// legitimate state only the app knows how to interpret, while a report that is
/// present and won't decode is a corrupt resource. CreditKit throws for both;
/// here they diverge.
public enum AppAttribution {
    /// Name of the generated resource inside the app bundle.
    static let resource = "attribution"

    /// The running app's report, read and decoded **once per process**.
    ///
    /// Prefer this to `current(bundle: .main)` at a call site that runs more
    /// than once. The report is an immutable resource in an immutable bundle,
    /// but it is not small — every notice is inlined — and the natural caller
    /// is a SwiftUI default argument, which Swift re-evaluates on every single
    /// `init`. `AboutSettingsView` is rebuilt on each body pass of the Settings
    /// stack, so reading eagerly there re-read the file, re-ran the decoder,
    /// and re-emitted a log line per keystroke in the search field.
    ///
    /// Same shape as `RegionDataSource.all`, the sibling default on that init.
    public static let main: AttributionManifest? = current(bundle: .main)

    /// Reads the attribution report out of `bundle`, or `nil` when the bundle
    /// carries none. The bundle is explicit (no default) so a caller can't
    /// accidentally read the wrong one; from the app, prefer ``main``, which
    /// caches this for `.main`.
    public static func current(bundle: Bundle) -> AttributionManifest? {
        do {
            let manifest = try AttributionManifest.load(from: bundle, resource: resource)
            logger { .loaded(creditCount: manifest.credits.count) }
            return manifest
        } catch AttributionError.reportMissing {
            logger { .noReport }
            return nil
        } catch {
            logger(attachments: [.error(error, name: "decode-error")]) {
                .decodeFailed(description: error.localizedDescription)
            }
            assertionFailure("Failed to decode the bundled attribution report: \(error)")
            return nil
        }
    }

    private static let logger = WhereLog.root(AppAttributionLog.self)
}
