import CreditKit
import Foundation

/// The Where app's attribution report, read back out of the bundle it ships in.
///
/// The report is generated by `./attribution` and committed into the app
/// target's resources, so — exactly like the commit `BuildInfo` reads — **only
/// the app target carries one**. A bundle that never received it (the
/// RegionViewer developer tool, `StuffTestHost`, an app extension) reports `nil`
/// rather than a placeholder, and the About screen says attribution is
/// unavailable instead of rendering empty sections that read as "nothing to
/// credit".
///
/// That distinction is the whole reason this sits above `CreditKit`: absent is a
/// legitimate state only the app knows how to interpret, while a report that is
/// present and won't decode is a corrupt resource. CreditKit throws for both;
/// here they diverge.
public enum AppAttribution {
    /// Name of the generated resource inside the app bundle.
    static let resource = "attribution"

    /// Reads the attribution report out of `bundle`, or `nil` when the bundle
    /// carries none. Pass `.main` from the app; the bundle is explicit (no
    /// default) so a caller can't accidentally read the wrong one.
    public static func current(bundle: Bundle) -> AttributionManifest? {
        do {
            let manifest = try AttributionManifest.load(from: bundle, resource: resource)
            logger { .loaded(creditCount: manifest.credits.count) }
            return manifest
        } catch AttributionError.reportMissing {
            logger { .noReport }
            return nil
        } catch {
            logger(attachments: [.error(error, name: "decode-error")]) {
                .decodeFailed(description: error.localizedDescription)
            }
            assertionFailure("Failed to decode the bundled attribution report: \(error)")
            return nil
        }
    }

    private static let logger = WhereLog.root(AppAttributionLog.self)
}
