#!/bin/bash
set -euo pipefail

# profile — deterministic, repeatable hot-spot report for Where's build and
# test times.
#
# It runs a clean `build-for-testing` (capturing Xcode's build-timing summary
# and any slow type-check warnings) and two test legs — the aggregate
# `Stuff-Workspace` scheme for the unit-test bundles, then the standalone
# `StuffSnapshotTests` scheme for the image-snapshot suite — reading
# authoritative per-test durations straight out of each .xcresult via
# xcresulttool. It then prints the slowest build phases, the slowest tests,
# and per-bundle totals, with both test legs folded into one report.
#
# The snapshot suite only runs via its own scheme: that scheme's test action
# carries the SNAPSHOT_EXPECTED_* / TZ environment pins the image comparisons
# rely on, and the capture pipeline is single-tenant, so the leg stays serial
# (xcodebuild's default — never add parallel-testing flags here; see the
# snapshot job in .github/workflows/ci.yml). The Stuff-Workspace leg skips
# the bundle (`-skip-testing`): Tuist's autogenerated scheme lists it, but
# running it there — without the env pins — compares timezone-baked
# references against the host's local clock, and would double-run the suite.
# `--no-snapshots` drops the snapshot leg (it adds ~10–15 min); the workspace
# leg still never runs the bundle.
#
# Report only: it never fails on slow numbers, it just calls them out — but a
# failing test leg aborts the run (exit non-zero) naming the leg and tailing
# its log, so a red snapshot suite (stale references on a branch, say) reads
# as a test failure, not a profile bug.
# Absolute wall times drift run to run, but the rankings and the structure of
# the report are stable, so it's useful for spotting regressions over time.
#
# Why raw xcodebuild instead of `tuist test`? Tuist's pretty formatter
# swallows `-showBuildTimingSummary`, and the .xcresult is the most reliable,
# formatter-independent source of per-test timings. We still let Tuist own
# project generation so a run always reflects the current manifests.

DEVICE="iPhone 17"
OS="27.0"
TOP=15
TEST_THRESHOLD="0.1"   # seconds — tests at/over this are flagged as hot spots
TC_THRESHOLD=100       # milliseconds — slow type-check warn threshold
DO_BUILD=true
DO_TESTS=true
DO_SNAPSHOTS=true

usage() {
    cat <<'USAGE'
Usage: ./profile [options]

Profiles Where's clean build and its test run — the unit-test bundles via the
Stuff-Workspace scheme plus the image-snapshot suite via its standalone
StuffSnapshotTests scheme — then prints the hot spots.

Options:
  --build-only              Only profile the build
  --tests-only              Only profile the tests
  --no-snapshots            Skip the StuffSnapshotTests leg (saves ~10-15 min)
  --device NAME             Simulator device name (default: "iPhone 17")
  --os VERSION              Simulator iOS version (default: "27.0")
  --top N                   How many slowest tests to list (default: 15)
  --test-threshold SECS     Flag tests at/over this many seconds (default: 0.1)
  --typecheck-threshold MS  Warn on type-check work over this many ms (default: 100)
  -h, --help                Show this help

Examples:
  ./profile
  ./profile --tests-only --no-snapshots --top 25 --test-threshold 0.2
  ./profile --device 'iPhone 17 Pro' --os 27.0
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        --build-only) DO_TESTS=false ;;
        --tests-only) DO_BUILD=false ;;
        --no-snapshots) DO_SNAPSHOTS=false ;;
        --device) shift; DEVICE="${1:?--device requires a value}" ;;
        --os) shift; OS="${1:?--os requires a value}" ;;
        --top) shift; TOP="${1:?--top requires a value}" ;;
        --test-threshold) shift; TEST_THRESHOLD="${1:?--test-threshold requires a value}" ;;
        --typecheck-threshold) shift; TC_THRESHOLD="${1:?--typecheck-threshold requires a value}" ;;
        -h|--help) usage; exit 0 ;;
        *) echo "error: unknown option '$1' (see ./profile --help)" >&2; exit 1 ;;
    esac
    shift
done

cd "$(dirname "$0")"

WORKSPACE="Stuff.xcworkspace"
SCHEME="Stuff-Workspace"
SNAPSHOT_SCHEME="StuffSnapshotTests"
# Boot the target up front and address it by UDID: a cold simulator otherwise
# lands in the timings as build/test cost, and a name-based destination can
# resolve to a same-named device on another runtime. `./simulator` hands back
# the device this checkout owns (creating it the first time), so a run in
# another checkout can't perturb these numbers by sharing it.
DESTINATION="platform=iOS Simulator,id=$(./simulator --device "$DEVICE" --os "$OS")"

WORKDIR="${TMPDIR:-/tmp}/where-profile"
DERIVED="$WORKDIR/DerivedData"
BUILD_LOG="$WORKDIR/build.log"
TEST_LOG="$WORKDIR/test.log"
RESULT_BUNDLE="$WORKDIR/tests.xcresult"
TESTS_JSON="$WORKDIR/tests.json"
SNAPSHOT_BUILD_LOG="$WORKDIR/snapshot-build.log"
SNAPSHOT_TEST_LOG="$WORKDIR/snapshot-test.log"
SNAPSHOT_RESULT_BUNDLE="$WORKDIR/snapshot-tests.xcresult"
SNAPSHOT_TESTS_JSON="$WORKDIR/snapshot-tests.json"
mkdir -p "$WORKDIR"

rule() { printf '%s\n' "============================================================"; }

# `$(inherited)` must reach xcodebuild literally; only $TC_THRESHOLD is ours.
# Shared by the clean workspace build and the snapshot scheme's incremental
# build below — identical settings are what let the second build reuse the
# first instead of recompiling the world.
tc_flags="\$(inherited) -Xfrontend -warn-long-function-bodies=$TC_THRESHOLD -Xfrontend -warn-long-expression-type-checking=$TC_THRESHOLD"

echo "==> Regenerating project (tuist generate --no-open)"
mise exec -- tuist generate --no-open >/dev/null

if [ "$DO_BUILD" = true ]; then
    echo "==> Clean build-for-testing on $DEVICE / iOS $OS (cold build)"
    SECONDS=0
    set +e
    xcodebuild clean build-for-testing \
        -workspace "$WORKSPACE" \
        -scheme "$SCHEME" \
        -destination "$DESTINATION" \
        -derivedDataPath "$DERIVED" \
        -showBuildTimingSummary \
        OTHER_SWIFT_FLAGS="$tc_flags" \
        >"$BUILD_LOG" 2>&1
    build_status=$?
    set -e
    build_wall=$SECONDS
    if [ "$build_status" -ne 0 ]; then
        echo "error: build failed (exit $build_status). Tail of $BUILD_LOG:" >&2
        tail -n 30 "$BUILD_LOG" >&2
        exit "$build_status"
    fi
    echo
    rule
    echo "BUILD HOT SPOTS  —  cold build wall: ${build_wall}s"
    rule
    # Parsing is best-effort: if xcodebuild's log format ever shifts, warn and
    # keep going rather than aborting the run with a traceback.
    set +e
    BUILD_LOG="$BUILD_LOG" TC_THRESHOLD="$TC_THRESHOLD" python3 - <<'PY'
import os, re, sys


def main():
    log = open(os.environ['BUILD_LOG'], errors='replace').read()

    phase_re = re.compile(r'^(.+?) \((\d+) tasks?\) \| ([\d.]+) seconds$', re.M)
    phases = [(m.group(1).strip(), int(m.group(2)), float(m.group(3)))
              for m in phase_re.finditer(log)]
    if phases:
        total = sum(p[2] for p in phases)
        print("Build phases (summed task-time across cores; wall is lower thanks to")
        print("parallelism — use the shares, not the absolute seconds):")
        for name, n, secs in sorted(phases, key=lambda x: -x[2]):
            pct = 100 * secs / total if total else 0
            print(f"  {secs:8.2f}s  {pct:4.0f}%  {name} ({n})")
    else:
        print("  (no build-timing summary found — was this a no-op incremental build?)")

    limit = int(os.environ['TC_THRESHOLD'])
    tc = re.findall(r'(/[^:\n]+:\d+:\d+): warning: (.*?took (\d+)ms to type-check.*)$',
                    log, re.M)
    print()
    if tc:
        print(f"Slow type-check sites (limit {limit}ms):")
        for loc, _msg, ms in sorted(tc, key=lambda x: -int(x[2])):
            short = re.sub(r'^.*?/((?:Where|Shared)/)', r'\1', loc)
            print(f"  {int(ms):6d}ms  {short}")
    else:
        print(f"Slow type-check sites (limit {limit}ms): none — no expression or")
        print("function body exceeded the threshold.")


try:
    main()
except Exception as exc:  # never hard-fail a reporting tool
    print(f"warning: couldn't parse build timing from {os.environ['BUILD_LOG']} ({exc})",
          file=sys.stderr)
    sys.exit(1)
PY
    set -e
    echo
fi

if [ "$DO_TESTS" = true ]; then
    if [ "$DO_BUILD" = true ]; then
        TEST_ACTION="test-without-building"
        TEST_WALL_LABEL="test-execution wall"
        echo "==> Running unit tests (test-without-building, reuses the build above)"
    else
        # `test` builds then tests, so the wall below includes compilation
        # (a full cold build on an empty DerivedData) — label it accordingly.
        TEST_ACTION="test"
        TEST_WALL_LABEL="build+test wall"
        echo "==> Running unit tests (build + test) on $DEVICE / iOS $OS"
    fi
    rm -rf "$RESULT_BUNDLE"
    SECONDS=0
    set +e
    # The autogenerated workspace scheme lists StuffSnapshotTests in its
    # test action, but the suite is only valid under its own scheme (env
    # pins, serial capture) — skip it here; the snapshot leg below runs it
    # properly.
    xcodebuild "$TEST_ACTION" \
        -workspace "$WORKSPACE" \
        -scheme "$SCHEME" \
        -destination "$DESTINATION" \
        -derivedDataPath "$DERIVED" \
        -resultBundlePath "$RESULT_BUNDLE" \
        -skip-testing:"$SNAPSHOT_SCHEME" \
        >"$TEST_LOG" 2>&1
    test_status=$?
    set -e
    test_wall=$SECONDS
    if [ "$test_status" -ne 0 ]; then
        echo "error: unit-test leg ($SCHEME) failed (exit $test_status). Tail of $TEST_LOG:" >&2
        tail -n 40 "$TEST_LOG" >&2
        exit "$test_status"
    fi
    xcrun xcresulttool get test-results tests --path "$RESULT_BUNDLE" >"$TESTS_JSON"
    TEST_JSON_PATHS="$TESTS_JSON"
    WALL_SUMMARY="$TEST_WALL_LABEL: ${test_wall}s"

    if [ "$DO_SNAPSHOTS" = true ]; then
        if [ "$DO_BUILD" = true ]; then
            # Same DerivedData, destination, and flags as the clean workspace
            # build above, whose build action already covers this bundle — so
            # this is a near-no-op that just guarantees the products before
            # test-without-building. Measured so the reuse stays visible if
            # it ever regresses into a real rebuild.
            echo "==> build-for-testing $SNAPSHOT_SCHEME (incremental, reuses the build above)"
            SECONDS=0
            set +e
            xcodebuild build-for-testing \
                -workspace "$WORKSPACE" \
                -scheme "$SNAPSHOT_SCHEME" \
                -destination "$DESTINATION" \
                -derivedDataPath "$DERIVED" \
                OTHER_SWIFT_FLAGS="$tc_flags" \
                >"$SNAPSHOT_BUILD_LOG" 2>&1
            snapshot_build_status=$?
            set -e
            snapshot_build_wall=$SECONDS
            if [ "$snapshot_build_status" -ne 0 ]; then
                echo "error: snapshot build ($SNAPSHOT_SCHEME) failed (exit $snapshot_build_status). Tail of $SNAPSHOT_BUILD_LOG:" >&2
                tail -n 30 "$SNAPSHOT_BUILD_LOG" >&2
                exit "$snapshot_build_status"
            fi
            echo "    incremental build: ${snapshot_build_wall}s"
            SNAPSHOT_TEST_ACTION="test-without-building"
            echo "==> Running snapshot tests (test-without-building, $SNAPSHOT_SCHEME scheme — serial by design, ~10-15 min)"
        else
            SNAPSHOT_TEST_ACTION="test"
            echo "==> Running snapshot tests (build + test, $SNAPSHOT_SCHEME scheme — serial by design, ~10-15 min)"
        fi
        rm -rf "$SNAPSHOT_RESULT_BUNDLE"
        SECONDS=0
        set +e
        xcodebuild "$SNAPSHOT_TEST_ACTION" \
            -workspace "$WORKSPACE" \
            -scheme "$SNAPSHOT_SCHEME" \
            -destination "$DESTINATION" \
            -derivedDataPath "$DERIVED" \
            -resultBundlePath "$SNAPSHOT_RESULT_BUNDLE" \
            >"$SNAPSHOT_TEST_LOG" 2>&1
        snapshot_status=$?
        set -e
        snapshot_wall=$SECONDS
        if [ "$snapshot_status" -ne 0 ]; then
            echo "error: snapshot-test leg ($SNAPSHOT_SCHEME) failed (exit $snapshot_status). Tail of $SNAPSHOT_TEST_LOG:" >&2
            tail -n 40 "$SNAPSHOT_TEST_LOG" >&2
            echo "note: a red snapshot leg usually means failed image comparisons (e.g. stale references on this branch), not a profile bug — rerun with --no-snapshots to profile without it." >&2
            exit "$snapshot_status"
        fi
        xcrun xcresulttool get test-results tests --path "$SNAPSHOT_RESULT_BUNDLE" >"$SNAPSHOT_TESTS_JSON"
        TEST_JSON_PATHS="$TESTS_JSON:$SNAPSHOT_TESTS_JSON"
        WALL_SUMMARY="$TEST_WALL_LABEL: ${test_wall}s (unit) + ${snapshot_wall}s (snapshot)"
    fi

    echo
    rule
    echo "TEST HOT SPOTS  —  $WALL_SUMMARY"
    rule
    # Best-effort parse: warn and continue if the xcresult schema shifts.
    set +e
    TESTS_JSON="$TEST_JSON_PATHS" TOP="$TOP" TEST_THRESHOLD="$TEST_THRESHOLD" python3 - <<'PY'
import json, os, sys
from collections import defaultdict


def main():
    cases = []  # (bundle, name, seconds)

    def walk(node, bundle):
        nt = node.get('nodeType')
        if nt == 'Unit test bundle':
            bundle = node.get('name', bundle)
        # `-skip-testing` can leave the skipped bundle's cases in the
        # workspace xcresult as zero-duration "Skipped" rows — not real runs,
        # so keep them out of the counts.
        if nt == 'Test Case' and node.get('result') != 'Skipped':
            cases.append((bundle, node.get('name', '?'),
                          float(node.get('durationInSeconds') or 0)))
        for child in node.get('children', []):
            walk(child, bundle)

    # One JSON per test leg (unit + snapshot), colon-separated; the bundles
    # are disjoint across legs, so the merged rows stay per-bundle exact.
    for path in os.environ['TESTS_JSON'].split(':'):
        data = json.load(open(path))
        for n in data.get('testNodes', []):
            walk(n, '?')

    top = int(os.environ['TOP'])
    thr = float(os.environ['TEST_THRESHOLD'])
    total = sum(d for _, _, d in cases)
    print(f"{len(cases)} tests, summed self-time {total:.2f}s")

    print()
    print(f"Slowest {top} tests:")
    for b, n, d in sorted(cases, key=lambda x: -x[2])[:top]:
        flag = '  <== over threshold' if d >= thr else ''
        print(f"  {d:7.3f}s  {b} / {n}{flag}")

    by = defaultdict(lambda: [0.0, 0])
    for b, _n, d in cases:
        by[b][0] += d
        by[b][1] += 1
    print()
    print("Per-bundle self-time:")
    for b, (d, c) in sorted(by.items(), key=lambda x: -x[1][0]):
        print(f"  {d:7.3f}s  {b} ({c} tests)")

    over = [c for c in cases if c[2] >= thr]
    print()
    if over:
        print(f"{len(over)} test(s) at/over the {thr}s threshold (flagged above).")
    else:
        print(f"No tests at/over the {thr}s threshold.")


try:
    main()
except Exception as exc:  # never hard-fail a reporting tool
    print(f"warning: couldn't parse test results from {os.environ['TESTS_JSON']} ({exc})",
          file=sys.stderr)
    sys.exit(1)
PY
    set -e
    echo
fi

echo "Logs and result bundles: $WORKDIR"
