#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "json"
require "open3"
require "optparse"
require "pathname"
require "tmpdir"

class UpgradeAndVerify
  GENERATED_MARKER = "// Generated by upgrade-where-backup; do not commit."
  PRESERVED_COLLECTIONS = %w[
    samples evidence manualDays dismissedIssues trackedRegions
    recordingDeviceProfiles recordingDeviceMetadataChanges recordingDeviceRemovals assets
  ].freeze

  def initialize(argv)
    @options = { force: false, keep_test: false }
    parser = OptionParser.new do |options|
      options.banner = "Usage: ruby upgrade_and_verify.rb INPUT [OUTPUT] [options]"
      options.on("--force", "Replace an existing output archive") { @options[:force] = true }
      options.on("--keep-test", "Keep the generated Swift test for debugging") { @options[:keep_test] = true }
      options.on("-h", "--help", "Show this help") do
        puts options
        exit
      end
    end
    arguments = parser.parse(argv)
    raise OptionParser::MissingArgument, "INPUT" if arguments.empty?
    raise OptionParser::InvalidArgument, "too many paths" if arguments.length > 2

    @input = File.expand_path(arguments.fetch(0))
    @output = File.expand_path(arguments[1] || default_output(@input))
    @repo_root = Pathname.new(__dir__).join("../../../..").expand_path.to_s
    @upgrader = File.join(@repo_root, "Where/Tools/upgrade-backup.rb")
    @test_template = File.join(
      @repo_root,
      ".agents/skills/upgrade-where-backup/assets/BackupUpgradeVerificationTests.swift.template",
    )
    @generated_test = File.join(
      @repo_root,
      "Where/WhereCore/Tests/BackupUpgradeVerificationTests.swift",
    )
  end

  def run
    validate_paths!
    source_manifest = read_manifest(@input)
    source_version = integer_format_version(source_manifest, "source")
    expected_counts = expected_counts(source_manifest)

    Dir.mktmpdir("where-backup-upgrade") do |work_directory|
      input_zip = if File.directory?(@input)
        zip_path = File.join(work_directory, "input.zip")
        run_command!("zip", "-q", "-r", zip_path, ".", chdir: @input)
        zip_path
      else
        @input
      end

      run_command!(
        "mise", "exec", "--", "ruby", @upgrader, input_zip, @output,
        chdir: @repo_root,
      )
    end

    run_command!("unzip", "-tq", @output)
    upgraded_manifest = read_manifest(@output)
    destination_version = integer_format_version(upgraded_manifest, "upgraded")
    current_version = upgrader_current_version
    fail_with("upgraded format is v#{destination_version}; expected v#{current_version}") unless destination_version == current_version
    verify_counts!(upgraded_manifest, expected_counts)
    run_swift_verification!(upgraded_manifest)

    puts "Verified Where backup v#{source_version} -> v#{destination_version}"
    puts "Output: #{@output}"
    puts "Counts: #{expected_counts.map { |key, count| "#{key}=#{count}" }.join(", ")}"
  end

  private

  def default_output(input)
    "#{input.sub(/\.zip\z/i, "")}-upgraded.zip"
  end

  def validate_paths!
    fail_with("input not found: #{@input}") unless File.exist?(@input)
    fail_with("upgrade script not found: #{@upgrader}") unless File.file?(@upgrader)
    fail_with("test template not found: #{@test_template}") unless File.file?(@test_template)
    fail_with("input and output resolve to the same path") if @input == @output
    fail_with("output already exists: #{@output} (pass --force only with approval)") if File.exist?(@output) && !@options[:force]
    fail_with("output directory not found: #{File.dirname(@output)}") unless File.directory?(File.dirname(@output))

    return unless File.exist?(@generated_test)

    marker = File.foreach(@generated_test).first&.chomp
    detail = marker == GENERATED_MARKER ? "left by an interrupted run" : "not owned by this skill"
    fail_with("generated test path already exists and is #{detail}: #{@generated_test}")
  end

  def read_manifest(path)
    contents = if File.directory?(path)
      manifest_path = File.join(path, "manifest.json")
      fail_with("manifest.json not found in backup directory: #{path}") unless File.file?(manifest_path)
      File.read(manifest_path)
    else
      stdout, stderr, status = Open3.capture3("unzip", "-p", path, "manifest.json")
      fail_with("could not read manifest.json from #{path}: #{stderr.strip}") unless status.success? && !stdout.empty?
      stdout
    end
    JSON.parse(contents)
  rescue JSON::ParserError => error
    fail_with("invalid manifest JSON in #{path}: #{error.message}")
  end

  def integer_format_version(manifest, label)
    version = manifest["formatVersion"]
    fail_with("#{label} manifest formatVersion must be an integer") unless version.is_a?(Integer)
    version
  end

  def expected_counts(manifest)
    counts = PRESERVED_COLLECTIONS.to_h do |key|
      value = manifest.fetch(key, [])
      fail_with("source manifest #{key} must be an array") unless value.is_a?(Array)
      [key, value.length]
    end
    primary_regions = manifest.fetch("primaryRegions", manifest.fetch("trackedRegions", []))
    fail_with("source manifest primaryRegions must be an array") unless primary_regions.is_a?(Array)
    counts.merge("primaryRegions" => primary_regions.length)
  end

  def verify_counts!(manifest, expected_counts)
    expected_counts.each do |key, expected|
      value = manifest[key]
      fail_with("upgraded manifest is missing array #{key}") unless value.is_a?(Array)
      fail_with("#{key} count changed from #{expected} to #{value.length}") unless value.length == expected
    end
  end

  def upgrader_current_version
    match = File.read(@upgrader).match(/^CURRENT_FORMAT_VERSION = (\d+)$/)
    fail_with("could not determine current format version from #{@upgrader}") unless match
    match[1].to_i
  end

  def run_swift_verification!(manifest)
    replacements = {
      "__BACKUP_PATH__" => JSON.generate(@output),
      "__SAMPLES_COUNT__" => manifest.fetch("samples").length.to_s,
      "__EVIDENCE_COUNT__" => manifest.fetch("evidence").length.to_s,
      "__MANUAL_DAYS_COUNT__" => manifest.fetch("manualDays").length.to_s,
      "__DISMISSED_ISSUES_COUNT__" => manifest.fetch("dismissedIssues").length.to_s,
      "__TRACKED_REGIONS_COUNT__" => manifest.fetch("trackedRegions").length.to_s,
      "__PRIMARY_REGIONS_COUNT__" => manifest.fetch("primaryRegions").length.to_s,
      "__DEVICE_PROFILES_COUNT__" => manifest.fetch("recordingDeviceProfiles").length.to_s,
      "__DEVICE_CHANGES_COUNT__" => manifest.fetch("recordingDeviceMetadataChanges").length.to_s,
      "__DEVICE_REMOVALS_COUNT__" => manifest.fetch("recordingDeviceRemovals").length.to_s,
      "__ASSETS_COUNT__" => manifest.fetch("assets").length.to_s,
    }
    test_source = replacements.reduce(File.read(@test_template)) do |source, (placeholder, value)|
      source.gsub(placeholder, value)
    end
    fail_with("unresolved placeholder in generated Swift test") if test_source.match?(/__[A-Z_]+__/)

    begin
      File.write(@generated_test, test_source)
      run_command!(
        "./test", "--only",
        "WhereCoreTests/BackupUpgradeVerificationTests/upgradedBackupDecodesAndLoadsAssets()",
        chdir: @repo_root,
      )
    ensure
      if @options[:keep_test]
        warn "Kept generated test: #{@generated_test}"
      else
        remove_generated_test!
      end
    end
  end

  def remove_generated_test!
    return unless File.exist?(@generated_test)

    marker = File.foreach(@generated_test).first&.chomp
    fail_with("refusing to remove generated test after its ownership marker changed") unless marker == GENERATED_MARKER
    FileUtils.rm_f(@generated_test)
  end

  def run_command!(*command, chdir: nil)
    success = chdir ? Dir.chdir(chdir) { system(*command) } : system(*command)
    fail_with("command failed: #{command.join(" ")}") unless success
  end

  def fail_with(message)
    raise RuntimeError, message
  end
end

begin
  UpgradeAndVerify.new(ARGV).run
rescue OptionParser::ParseError, RuntimeError => error
  warn "error: #{error.message}"
  exit 1
end
