#if DEBUG
    import CoreTransferable
    import Foundation
    import UniformTypeIdentifiers

    struct CardDesignerJSONExport: Transferable {
        let data: Data

        static var transferRepresentation: some TransferRepresentation {
            DataRepresentation(exportedContentType: .json) { $0.data }
                .suggestedFileName("Where Card Design.json")
        }
    }

    struct CardDesignerSwiftExport: Transferable {
        let source: String

        static var transferRepresentation: some TransferRepresentation {
            DataRepresentation(exportedContentType: .plainText) {
                Data($0.source.utf8)
            }
            .suggestedFileName("Where Card Design.swift")
        }
    }

    enum CardDesignerSwiftExporter {
        static func source(for configuration: CardDesignerConfiguration) -> String {
            """
            // Generated by Where's DEBUG Card Designer Studio (schema \(configuration
                .schemaVersion)).
            // Paste these values into WhereStylesheet.CardStyles.standard.

            let regularCardStyle = \(card(configuration.regular))

            let compactCardStyle = \(card(configuration.compact))

            let lightCardStyles = \(cardStyles(
                configuration,
                securityPrint: configuration.shared.lightSecurityPrint,
            ))

            let darkCardStyles = \(cardStyles(
                configuration,
                securityPrint: configuration.shared.darkSecurityPrint,
            ))
            """
        }

        private static func card(_ card: CardDesignerConfiguration.Card) -> String {
            """
            WhereStylesheet.CardStyle(
                cornerRadius: \(number(card.cornerRadius)),
                padding: \(number(card.padding)),
                contentSpacing: \(number(card.contentSpacing)),
                progressBarHeight: \(number(card.progressBarHeight)),
                entryStamp: \(entryStamp(card.entryStamp, indent: 1)),
                regionNameTypography: \(typography(card.regionNameTypography)),
                regionNameTracking: \(number(card.regionNameTracking)),
                heroNumberTypography: \(typography(card.heroNumberTypography)),
                dayUnitTypography: \(typography(card.dayUnitTypography)),
                watermarkFontSize: \(number(card.watermarkFontSize)),
                watermarkOffset: CGSize(width: \(number(card.watermarkOffset
                        .x)), height: \(number(card.watermarkOffset.y))),
                regionShape: \(regionShape(card.regionShape, indent: 1)),
                sheen: .init(
                    intensity: \(number(card.sheen.intensity)),
                    staticGlintIntensity: \(number(card.sheen.staticGlintIntensity)),
                    staticPose: .init(roll: \(number(card.sheen.staticRoll)), pitch: \(number(card
                            .sheen.staticPitch))),
                ),
                rosette: .init(
                    wobble: \(number(card.rosette.wobble)),
                    lineWidth: \(number(card.rosette.lineWidth)),
                    primaryRingSpacing: \(number(card.rosette.primaryRingSpacing)),
                    secondaryRingSpacing: \(number(card.rosette.secondaryRingSpacing)),
                ),
                glow: .init(opacity: \(number(card.glow.opacity)), radius: \(number(card.glow
                        .radius)), offsetY: \(number(card.glow.offsetY))),
                lift: .init(opacity: \(number(card.lift.opacity)), radius: \(number(card.lift
                        .radius)), offsetY: \(number(card.lift.offsetY))),
            )
            """
        }

        private static func cardStyles(
            _ configuration: CardDesignerConfiguration,
            securityPrint: CardDesignerConfiguration.SecurityPrint,
        ) -> String {
            let shared = configuration.shared
            return """
            WhereStylesheet.CardStyles(
                regular: regularCardStyle,
                compact: compactCardStyle,
                watermarkOpacity: \(number(shared.watermarkOpacity)),
                glassTintOpacity: \(number(shared.glassTintOpacity)),
                nameOpacity: \(number(shared.nameOpacity)),
                rosetteFill: .init(
                    primary: \(number(shared.primaryRosetteOpacity)),
                    secondary: \(number(shared.secondaryRosetteOpacity)),
                ),
                securityPrint: .init(
                    whiteMix: \(number(securityPrint.whiteMix)),
                    backgroundBlendMode: .\(securityPrint.blendMode.rawValue),
                ),
                dayCount: .standard,
            )
            """
        }

        private static func typography(_ typography: CardDesignerConfiguration
            .Typography) -> String
        {
            let size = switch typography.size {
                case let .fixed(points): ".fixed(\(number(points)))"
                case let .semantic(style): ".semantic(.\(style.rawValue))"
            }
            return ".init(size: \(size), weight: .\(typography.weight.rawValue), design: .\(typography.design.rawValue))"
        }

        private static func entryStamp(
            _ stamp: CardDesignerConfiguration.EntryStamp,
            indent: Int,
        ) -> String {
            let arc = stamp.arc.map { arc($0, indent: indent + 1) } ?? "nil"
            return """
            .init(
            \(spaces(indent + 1))size: \(number(stamp.size)),
            \(spaces(indent + 1))outerRing: .init(opacity: \(number(stamp.outerRing
                    .opacity)), lineWidthFraction: \(number(stamp.outerRing.lineWidthFraction))),
            \(spaces(indent + 1))innerRing: .init(
            \(spaces(indent + 2))opacity: \(number(stamp.innerRing.opacity)),
            \(spaces(indent + 2))lineWidthFraction: \(number(stamp.innerRing.lineWidthFraction)),
            \(spaces(indent + 2))dash: .init(lengthFraction: \(number(stamp.innerRing
                    .dashLengthFraction)), spacingFraction: \(number(stamp.innerRing
                    .dashSpacingFraction))),
            \(spaces(indent + 2))insetFraction: \(number(stamp.innerRing.insetFraction)),
            \(spaces(indent + 1))),
            \(spaces(indent + 1))content: .init(
            \(spaces(indent + 2))spacingFraction: \(number(stamp.content.spacingFraction)),
            \(spaces(indent + 2))artworkExtent: CGSize(width: \(number(stamp.content.artworkExtent
                    .width)), height: \(number(stamp.content.artworkExtent.height))),
            \(spaces(indent + 2))symbolFont: \(fractionalTypography(stamp.content.symbolFont)),
            \(spaces(indent + 2))yearFont: \(fractionalTypography(stamp.content.yearFont)),
            \(spaces(indent + 2))opacity: \(number(stamp.content.opacity)),
            \(spaces(indent + 1))),
            \(spaces(indent + 1))arc: \(arc),
            \(spaces(indent + 1))rotationDegrees: \(number(stamp.rotationDegrees)),
            \(spaces(indent)))
            """
        }

        private static func arc(
            _ arc: CardDesignerConfiguration.Arc,
            indent: Int,
        ) -> String {
            """
            .init(
            \(spaces(indent + 1))radiusFraction: \(number(arc.radiusFraction)),
            \(spaces(indent + 1))font: \(fractionalTypography(arc.font)),
            \(spaces(indent + 1))opacity: \(number(arc.opacity)),
            \(spaces(indent + 1))maximumSweepDegrees: \(number(arc.maximumSweepDegrees)),
            \(spaces(indent + 1))sweepDegreesPerCharacter: \(number(arc.sweepDegreesPerCharacter)),
            \(spaces(indent)))
            """
        }

        private static func fractionalTypography(
            _ typography: CardDesignerConfiguration.FractionalTypography,
        ) -> String {
            ".init(sizeFraction: \(number(typography.sizeFraction)), weight: .\(typography.weight.rawValue), design: .\(typography.design.rawValue))"
        }

        private static func regionShape(
            _ shape: CardDesignerConfiguration.RegionShape?,
            indent: Int,
        ) -> String {
            guard let shape else { return "nil" }
            return """
            .init(
            \(spaces(indent + 1))watermark: \(artwork(shape.watermark, indent: indent + 1)),
            \(spaces(indent + 1))stamp: \(artwork(shape.stamp, indent: indent + 1)),
            \(spaces(indent + 1))securityBorder: .init(
            \(spaces(indent + 2))inset: \(number(shape.securityBorder.inset)),
            \(spaces(indent + 2))glyphSize: \(number(shape.securityBorder.glyphSize)),
            \(spaces(indent + 2))spacing: \(number(shape.securityBorder.spacing)),
            \(spaces(indent + 2))opacity: \(number(shape.securityBorder.opacity)),
            \(spaces(indent + 1))),
            \(spaces(indent)))
            """
        }

        private static func artwork(
            _ artwork: CardDesignerConfiguration.Artwork,
            indent: Int,
        ) -> String {
            let stroke = artwork.stroke.map {
                ".init(opacity: \(number($0.opacity)), width: \(number($0.width)))"
            } ?? "nil"
            return """
            .init(
            \(spaces(indent + 1))center: CGPoint(x: \(number(artwork.center.x)), y: \(number(artwork
                    .center.y))),
            \(spaces(indent + 1))extent: CGSize(width: \(number(artwork.extent
                    .width)), height: \(number(artwork.extent.height))),
            \(spaces(indent + 1))scale: \(number(artwork.scale)),
            \(spaces(indent + 1))fillOpacity: \(number(artwork.fillOpacity)),
            \(spaces(indent + 1))stroke: \(stroke),
            \(spaces(indent)))
            """
        }

        private static func number(_ value: some BinaryFloatingPoint) -> String {
            var formatted = String(
                format: "%.4f",
                locale: Locale(identifier: "en_US_POSIX"),
                Double(value),
            )
            while formatted.last == "0" {
                formatted.removeLast()
            }
            if formatted.last == "." { formatted.removeLast() }
            return formatted == "-0" ? "0" : formatted
        }

        private static func spaces(_ level: Int) -> String {
            String(repeating: "    ", count: level)
        }
    }
#endif
