@testable import PeriscopeMacros
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import Testing

private let macros: [String: any Macro.Type] = [
    "LogEvent": LogEventMacro.self,
    "LogScope": LogScopeMacro.self,
]

@Test func rejectsConditionalEventMembers() {
    let declaration: DeclSyntax = """
    struct Event {
        #if DEBUG
        @LogField(exposure: .shareable, kind: .count) var count: String
        #endif
    }
    """
    let parsed = LogEventMacro.parseFields(declaration.cast(StructDeclSyntax.self))
    #expect(parsed.hasError)
    #expect(parsed.diagnostics.map(\.id) == ["conditional-event-member"])
}

@Test(arguments: [
    "Policy.shareable, kind: .count",
    ".shareable, kind: Policy.count",
    "LogFieldExposure.shareable, kind: .count",
])
func rejectsQualifiedClassifications(classification: String) {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                @LogField(exposure: \(classification))
                var count: Int
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                @LogField(exposure: \(classification))
                var count: Int
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [DiagnosticSpec(
            message: "stored event properties require a complete @LogField classification",
            line: 5,
            column: 9,
        )],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test func rejectsStaticClassifiedFields() {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                @LogField(exposure: .shareable, kind: .count)
                static var count: Int
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                @LogField(exposure: .shareable, kind: .count)
                static var count: Int
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [DiagnosticSpec(
            message: "@LogField requires an instance property",
            line: 5,
            column: 9,
        )],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test func rejectsControlledShareableFields() {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                @LogField(exposure: .shareable, kind: .count, export: .never)
                var count: Int
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                @LogField(exposure: .shareable, kind: .count, export: .never)
                var count: Int
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [DiagnosticSpec(
            message: "export controls require a restricted field; shareable fields already approve baseline export",
            line: 5,
            column: 9,
        )],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test(
    arguments: ["exportedValue", "exportDescription", "`exportedValue`", "`exportDescription`"],
    ["var", "func"],
)
func rejectsExportProjectionCollision(name: String, kind: String) {
    let member = kind == "var" ? "var \(name): String { \"value\" }" : "func \(name)() {}"
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                \(member)
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                \(member)
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [DiagnosticSpec(
            message: "\(name.filter { $0 != "`" }) is generated by @LogEvent",
            line: 5,
            column: 9,
        )],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test(arguments: ["", "\"sample_count\", "])
func rejectsResolvedFieldKeyCollisions(key: String) {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                @LogField(exposure: .shareable, kind: .count)
                var sampleCount: Int
                @LogField(\(key)exposure: .shareable, kind: .count)
                var sample_count: Int
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                @LogField(exposure: .shareable, kind: .count)
                var sampleCount: Int
                @LogField(\(key)exposure: .shareable, kind: .count)
                var sample_count: Int
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [DiagnosticSpec(
            message: "event field key 'sample_count' is duplicated",
            line: 7,
            column: 9,
        )],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test(arguments: [
    "\"\", ": "sampleCount",
    "key, ": "sampleCount",
    "\"\\(key)\", ": "sampleCount",
    "": "café",
])
func rejectsInvalidFieldKeys(key: String, property: String) {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                @LogField(\(key)exposure: .shareable, kind: .count)
                var \(property): Int
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                @LogField(\(key)exposure: .shareable, kind: .count)
                var \(property): Int
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [DiagnosticSpec(
            message: "use a nonempty string-literal field key or omit it for an ASCII property name",
            line: 5,
            column: 9,
        )],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test(arguments: ["\"count\", ", ""])
func expandsClassifiedEventAndLogMethod(key: String) {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("counted", level: .notice, message: "Counted")
            struct Counted {
                @LogField(\(key)exposure: .shareable, kind: .count)
                var count: Int
            }
        }
        """,
        expandedSource: """
        enum SampleLog {
            struct Counted {
                @LogField(\(key)exposure: .shareable, kind: .count)
                var count: Int

                static let eventName = SampleLog.scopeName + ".counted"

                static let eventVersion = 1

                private enum CodingKeys: String, CodingKey {
                        case count = "count"
                }

                init(
                        count: PeriscopeCore.ClassifiedLogInput<PeriscopeCore.LogFieldPolicy.Shared, PeriscopeCore.LogFieldPolicy.Count, Int>
                ) {
                        self._count = PeriscopeCore.LogField(wrappedValue: count.value, "count", exposure: .shareable, kind: .count)
                }

                var classifiedFields: [PeriscopeCore.ClassifiedLogField] {
                    var fields: [PeriscopeCore.ClassifiedLogField] = []
                        if let field = PeriscopeCore.LogFieldProjection.count(self.count, key: PeriscopeCore.LogFieldKey("count")) {
                        fields.append(field)
                    }
                    return fields
                }

                var exportDescription: PeriscopeCore.LogExportDescription {
                    PeriscopeCore.LogExportDescription.object([
                        PeriscopeCore.LogExportField(PeriscopeCore.LogFieldKey("count"), value: self.count, requirements: .classified(exposure: .shareable, kind: .count))
                    ])
                }

                struct LogMethod {
                    fileprivate let log: PeriscopeCore.Log<SampleLog>

                    func callAsFunction(
                        count: PeriscopeCore.ClassifiedLogInput<PeriscopeCore.LogFieldPolicy.Shared, PeriscopeCore.LogFieldPolicy.Count, Int>,
                        attachments: [PeriscopeCore.LogAttachment] = [],
                        function: StaticString = #function,
                        fileID: StaticString = #fileID
                    ) {
                        self.log.record(
                            SampleLog.Counted(
                                count: count
                            ),
                            attachments: attachments,
                            function: function,
                            fileID: fileID
                        )
                    }
                }

                func exportedValue(using policy: PeriscopeCore.LogExportPolicy) throws -> PeriscopeCore.JSONValue {
                    try exportDescription.exportedValue(using: policy)
                }

                var level: PeriscopeCore.LogLevel {
                    .notice
                }

                var message: String {
                    "Counted"
                }

                var externalID: String? {
                    nil
                }

                static var isProtectedFromDropping: Bool {
                    false
                }
            }

            static let scopeName = "Sample"

            struct LogMethods {
                fileprivate let log: PeriscopeCore.Log<SampleLog>

                var `counted`: Counted.LogMethod {
                    Counted.LogMethod(log: log)
                }
            }

            static func makeLogMethods(_ log: PeriscopeCore.Log<SampleLog>) -> LogMethods {
                LogMethods(log: log)
            }
        }

        extension SampleLog.Counted: PeriscopeCore.LogEvent {
        }

        extension SampleLog: PeriscopeCore.LogScopeDefinition {
        }
        """,
        macros: macros,
    )
}

@Test
func eventRequiresStruct() {
    assertMacroExpansion(
        "@LogEvent(\"value\", message: \"Value\") enum Value {}",
        expandedSource: "enum Value {}",
        diagnostics: [
            DiagnosticSpec(message: "@LogEvent requires a struct", line: 1, column: 1),
        ],
        macros: macros,
    )
}

@Test
func eventRequiresScope() {
    assertMacroExpansion(
        "@LogEvent(\"value\", message: \"Value\") struct Value {}",
        expandedSource: "struct Value {}",
        diagnostics: [
            DiagnosticSpec(
                message: "@LogEvent must be nested directly in an @LogScope enum",
                line: 1,
                column: 1,
            ),
        ],
        macros: macros,
    )
}

@Test
func eventRequiresAMessage() {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event")
            struct Event {}
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {}
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [
            DiagnosticSpec(
                message: "an event requires a static or instance message",
                line: 3,
                column: 5,
            ),
        ],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test
func eventRejectsInvalidIdentifiersAndVersions() {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("", message: "Event")
            struct Event {}
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {}
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [
            DiagnosticSpec(
                message: "@LogEvent requires a nonempty string-literal event ID",
                line: 3,
                column: 5,
            ),
        ],
        macros: ["LogEvent": LogEventMacro.self],
    )

    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event", version: 0)
            struct Event {}
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {}
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [
            DiagnosticSpec(
                message: "version must be a positive integer literal",
                line: 3,
                column: 42,
            ),
        ],
        macros: ["LogEvent": LogEventMacro.self],
    )
}

@Test
func eventRejectsUnclassifiedAndInvalidShareableFields() {
    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                var count: Int
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                var count: Int
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [
            DiagnosticSpec(
                message: "stored event properties require a complete @LogField classification",
                line: 5,
                column: 9,
            ),
        ],
        macros: ["LogEvent": LogEventMacro.self],
    )

    assertMacroExpansion(
        """
        @LogScope("Sample")
        enum SampleLog {
            @LogEvent("event", message: "Event")
            struct Event {
                @LogField("value", exposure: .shareable, kind: .identifier)
                var value: String
            }
        }
        """,
        expandedSource: """
        @LogScope("Sample")
        enum SampleLog {
            struct Event {
                @LogField("value", exposure: .shareable, kind: .identifier)
                var value: String
            }
        }

        extension SampleLog.Event: PeriscopeCore.LogEvent {
        }
        """,
        diagnostics: [
            DiagnosticSpec(
                message: "field kind '.identifier' cannot be shareable",
                line: 5,
                column: 9,
            ),
        ],
        macros: ["LogEvent": LogEventMacro.self],
    )
}
