import Foundation
import SwiftParser
import SwiftSyntax

/// Emits ordinary Swift calls. Unsupported declarations remain visible with their reason.
struct BindingEmitter {
    // Keep metadata construction bounded. Each batch runs synchronously on the registry actor.
    static let registrationsPerBatch = 16
    let planner: BindingPlanner
    let inventories: [SourceInventory]

    init(planner: BindingPlanner, inventories: [SourceInventory] = []) {
        self.planner = planner
        self.inventories = inventories
    }

    func emit() throws -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
        let archive = try encoder.encode(planner.module.files + inventories.flatMap(\.module.files))
        let coverage = try encoder.encode(SourceCoverage(
            planner: planner,
            inventories: inventories,
        ))
        var lines = [
            "// Generated by PortholeGenerator. Do not edit.",
            "import Foundation",
            "import PortholeRuntime",
        ]
        for file in planner.module.files {
            let imports = ImportCollector()
            imports.walk(Parser.parse(source: file.content))
            lines += imports.declarations
        }
        lines += [
            "public enum PortholeGeneratedModule {",
            "#if DEBUG",
            "    public static let isCompiledWithDebugCondition = true",
            "#else",
            "    public static let isCompiledWithDebugCondition = false",
            "#endif",
            "    public static let sourceArchiveJSON = \(literal(String(decoding: archive, as: UTF8.self)))",
            "    public static let coverageJSON = \(literal(String(decoding: coverage, as: UTF8.self)))",
            "    public static func install(in registry: PortholeRegistry, scope: PortholeScopeToken) async throws {",
            "        try await registry.installSourceArchive(sourceArchiveJSON, in: scope)",
            "        for batch in registrationBatches {",
            "            try Task.checkCancellation()",
            "            try await batch(registry, scope)",
            "        }",
            "        try Task.checkCancellation()",
            "        try await registry.installCoverage(coverageJSON, in: scope)",
            "    }",
        ]
        var registrations: [[String]] = []
        for (index, declaration) in planner.module.declarations.enumerated() {
            let binding = planner.plan(declaration)
            registrations.append(conditional(
                declaration.conditions,
                body: registration(
                    binding,
                    index: index,
                    moduleName: planner.module.name,
                    availability: SourceCoverage
                        .availability(unsupportedReason: binding.unsupportedReason),
                ),
            ))
        }
        var inventoryIndex = planner.module.declarations.count
        for inventory in inventories {
            let inventoryPlanner = BindingPlanner(module: inventory.module, dependencyModules: [])
            for declaration in inventory.module.declarations {
                // No conditional imports or type references: inactive declarations remain evidence.
                registrations.append(registration(
                    inventoryPlanner.plan(declaration),
                    index: inventoryIndex,
                    moduleName: inventory.module.name,
                    availability: .unsupported(inventory.reason),
                ))
                inventoryIndex += 1
            }
            for file in inventory.excludedFiles {
                registrations.append(excludedFileRegistration(
                    file,
                    moduleName: inventory.module.name,
                    index: inventoryIndex,
                ))
                inventoryIndex += 1
            }
        }
        let batches = stride(from: 0, to: registrations.count, by: Self.registrationsPerBatch)
            .map { start in
                Array(registrations[start ..< min(
                    start + Self.registrationsPerBatch,
                    registrations.count,
                )])
            }
        lines += [
            "    private typealias RegistrationBatch = @Sendable (PortholeRegistry, PortholeScopeToken) async throws -> Void",
            "    private static let registrationBatches: [RegistrationBatch] = [",
        ]
        lines += batches.indices.map {
            "        { registry, scope in try await installBatch\($0)(registry, scope) },"
        }
        lines += ["    ]"]
        for (index, batch) in batches.enumerated() {
            lines += [
                "    private static func installBatch\(index)(_ registry: isolated PortholeRegistry, _ scope: PortholeScopeToken) throws {",
            ]
            lines += batch.flatMap(\.self)
            lines += ["    }"]
        }
        for (index, declaration) in planner.module.declarations.enumerated() {
            let binding = planner.plan(declaration)
            if binding.unsupportedReason == nil {
                lines += conditional(
                    declaration.conditions,
                    body: ["#if !PORTHOLE_ORIGINAL_SOURCE_CHECK"] + thunk(binding, index: index) +
                        ["#endif"],
                )
            }
        }
        lines += ["}"]
        for (index, declaration) in planner.module.declarations.enumerated() {
            let binding = planner.plan(declaration)
            if binding.unsupportedReason == nil, usesActorThunk(binding),
               let owner = declaration.owner
            {
                let parameters = declaration.parameters.enumerated().map { offset, parameter in
                    "_ value\(offset): \(planner.qualifiedType(parameter.type, owner: owner))"
                }.joined(separator: ", ")
                let action: String
                if declaration.kind == .propertySetter {
                    action = "self.\(escapedIdentifier(declaration.name)) = value0"
                } else {
                    let arguments = nativeArguments(declaration)
                    action = "return \(declaration.isThrowing ? "try " : "")self.\(escapedIdentifier(declaration.name))(\(arguments))"
                }
                lines += conditional(declaration.conditions, body: [
                    "#if !PORTHOLE_ORIGINAL_SOURCE_CHECK",
                    "extension \(owner) {",
                    "    fileprivate func _portholeCall\(index)(\(parameters)) throws -> \(planner.qualifiedType(declaration.resultType ?? "Void", owner: owner)) {",
                    "        try Task.checkCancellation()",
                    "        \(action)",
                    "    }",
                    "}",
                    "#endif",
                ])
            }
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private func registration(
        _ binding: BindingPlanner.Binding,
        index: Int,
        moduleName: String,
        availability: SourceCoverage.Availability,
    ) -> [String] {
        let declaration = binding.declaration
        let availabilitySource = switch availability {
            case .callable: ".callable"
            case .inspectable: ".inspectable"
            case let .unsupported(reason): ".unsupported(\(literal(reason)))"
        }
        let qualifiedName = (declaration.owner.map { "\($0).\(declaration.name)" } ?? declaration
            .name)
            + (declaration.kind == .propertySetter ? ".set" : "")
        let parameters = declaration.parameters.map { parameter in
            "PortholeParameter(name: \(literal(parameter.name)), summary: \(literal(parameterSummary(parameter, declaration: declaration))), schema: \(transferSchema(parameter.type, binding: binding)), required: true)"
        }.joined(separator: ", ")
        let effect = declaration.kind == .enumerationInspection ? ".read" :
            declaration.kind == .propertySetter ? ".mutation" : planner
            .hasKnownStoredGetter(declaration) ? ".read" : ".unknown"
        let resultSchema = declaration.kind == .enumerationInspection ? enumInspectionSchema :
            transferSchema(declaration.resultType ?? "Void", binding: binding)
        var summary = declaration.documentation.isEmpty ? declaration.signature : declaration
            .documentation
        if declaration.kind == .enumerationInspection {
            summary = "Inspect the active case and named associated values without invoking getters or application encoders. Complex payloads use typed scoped handles."
        }
        if planner.resultSerializationRequiresApproval(declaration) {
            summary += "\nResult serialization can execute application Encodable code and requires approval."
        }
        var lines = [
            "        let capability\(index) = PortholeCapability(",
            "            id: .init(rawValue: \(literal(declaration.declarationID))), module: .init(rawValue: \(literal(moduleName))),",
            "            name: \(literal(qualifiedName)), summary: \(literal(summary)),",
            "            parameters: [\(parameters)], result: \(resultSchema), effect: \(effect),",
            "            source: .init(path: \(literal(declaration.file)), line: \(declaration.line)), ownership: \(ownership(binding)), availability: \(availabilitySource))",
        ]
        if availability == .callable {
            lines += [
                "#if PORTHOLE_ORIGINAL_SOURCE_CHECK",
                "        try registry.describe(capability\(index), in: scope)",
                "#else",
                "        try registry.register(capability\(index), in: scope) { invocation, registry in",
                "            try await invoke\(index)(invocation, registry: registry)",
                "        }",
                "#endif",
            ]
        } else {
            lines.append("        try registry.describe(capability\(index), in: scope)")
        }
        return lines
    }

    private func excludedFileRegistration(
        _ file: SourceInventory.ExcludedFile,
        moduleName: String,
        index: Int,
    ) -> [String] {
        [
            "        let capability\(index) = PortholeCapability(",
            "            id: .init(rawValue: \(literal("\(moduleName):excluded-source:\(file.path)"))), module: .init(rawValue: \(literal(moduleName))),",
            "            name: \(literal(file.path)), summary: \(literal(file.reason)), parameters: [], result: .any, effect: .unknown,",
            "            source: nil, ownership: .adapter, availability: .unsupported(\(literal(file.reason))))",
            "        try registry.describe(capability\(index), in: scope)",
        ]
    }

    private func ownership(_ binding: BindingPlanner.Binding) -> String {
        if binding.isMainActor { return ".mainActor" }
        if binding.isActor, !binding.declaration.isStatic, let owner = binding.receiverType {
            return ".actorInstance(typeName: \(literal(owner)))"
        }
        return ".unisolated"
    }

    private func thunk(_ binding: BindingPlanner.Binding, index: Int) -> [String] {
        let declaration = binding.declaration
        var lines: [String] = []
        if binding.isMainActor { lines.append("    @MainActor") }
        lines
            .append(
                "    private static func invoke\(index)(_ invocation: PortholeInvocation, registry: PortholeRegistry) async throws -> PortholeValue {",
            )
        if let receiver = binding.receiverType {
            if !planner.isSendable(receiver, relativeTo: declaration.owner), binding.isMainActor {
                lines += [
                    "        let receiverBox = try await registry.resolveMainActor(invocation.receiver, as: PortholeMainActorValue<\(receiver)>.self, in: invocation.scope)",
                    "        let receiver = receiverBox.value",
                ]
            } else {
                lines
                    .append(
                        "        let receiver = try await registry.resolve(invocation.receiver, as: (\(receiver)).self, in: invocation.scope)",
                    )
            }
        }
        if declaration.kind == .enumerationInspection {
            return lines + enumInspection(binding) + ["    }"]
        }
        for (argumentIndex, parameter) in declaration.parameters.enumerated() {
            let key = parameter.name
            lines
                .append(
                    "        guard let argument\(argumentIndex) = invocation.arguments[\(literal(key))] else { throw PortholeError.invalidArguments(\(literal("Missing argument '\(key)'."))) }",
                )
            let type = planner.qualifiedType(parameter.type, owner: declaration.owner)
            if ["Void", "()"].contains(parameter.type) {
                lines += [
                    "        guard argument\(argumentIndex) == .null else { throw PortholeError.invalidArguments(\(literal("Argument '\(key)' requires null for Void."))) }",
                    "        let value\(argumentIndex): \(type) = ()",
                ]
            } else if parameter.type == "Character" {
                lines += [
                    "        guard case let .string(text\(argumentIndex)) = argument\(argumentIndex), text\(argumentIndex).count == 1, let value\(argumentIndex) = text\(argumentIndex).first else { throw PortholeError.invalidArguments(\(literal("Argument '\(key)' requires one Character."))) }",
                ]
            } else if parameter.type == "Substring" {
                lines += [
                    "        let text\(argumentIndex) = try await registry.decode(argument\(argumentIndex), as: String.self, in: invocation.scope)",
                    "        let value\(argumentIndex) = Substring(text\(argumentIndex))",
                ]
            } else if !planner.isSendable(parameter.type, relativeTo: declaration.owner),
                      binding.isMainActor
            {
                lines += [
                    "        let argumentBox\(argumentIndex) = try await registry.decodeMainActor(argument\(argumentIndex), as: PortholeMainActorValue<\(type)>.self, in: invocation.scope)",
                    "        let value\(argumentIndex): \(type) = argumentBox\(argumentIndex).value",
                ]
            } else {
                lines
                    .append(
                        "        let value\(argumentIndex): \(type) = try await registry.decode(argument\(argumentIndex), as: (\(type)).self, in: invocation.scope)",
                    )
            }
        }
        let arguments = nativeArguments(declaration)
        let target: String
        if usesActorThunk(binding) {
            let values = declaration.parameters.indices.map { "value\($0)" }.joined(separator: ", ")
            target = "receiver._portholeCall\(index)(\(values))"
        } else if declaration.kind == .propertySetter {
            let base = binding.receiverType != nil ? "receiver." : declaration.owner
                .map { "\($0)." } ?? ""
            target = base + escapedIdentifier(declaration.name) + " = value0"
        } else if declaration.kind == .initializer {
            target = "\(declaration.owner ?? declaration.name)(\(arguments))"
        } else if declaration.kind == .enumerationCase {
            let base = declaration.owner.map { "\($0)." } ?? ""
            target = base + escapedIdentifier(declaration.name) +
                (declaration.parameters.isEmpty ? "" : "(\(arguments))")
        } else {
            let base = binding.receiverType != nil ? "receiver." : declaration.owner
                .map { "\($0)." } ?? ""
            target = base + escapedIdentifier(declaration.name) +
                (declaration.kind == .function ? "(\(arguments))" : "")
        }
        // Same-module reads of an actor's immutable Sendable storage are synchronous.
        let crossesActor = binding.isActor && !declaration.isStatic &&
            !planner.isSynchronousActorConstant(declaration)
        let prefix = (declaration.isThrowing || usesActorThunk(binding) ? "try " : "") +
            (declaration.isAsync || crossesActor ? "await " : "")
        let call: String
        if !declaration.isAsync, !usesActorThunk(binding),
           [.function, .initializer, .enumerationCase].contains(declaration.kind)
        {
            // A synchronous context selects the declared sync overload even when an async overload
            // exists on an inherited protocol. The closure stays on the helper's current executor.
            let result = planner.qualifiedType(
                declaration.resultType ?? "Void",
                owner: declaration.owner,
            )
            let throwing = declaration.isThrowing ? " throws" : ""
            let attempt = declaration.isThrowing ? "try " : ""
            call = "\(attempt){ ()\(throwing) -> \(result) in \(attempt)\(target) }()"
        } else {
            call = prefix + target
        }
        lines.append("        try Task.checkCancellation()")
        if ["Void", "()"].contains(declaration.resultType ?? "Void") {
            let discard = declaration.kind == .function ? "let _: Void = " : ""
            lines += ["        \(discard)\(call)", "        return .null"]
        } else if [.initializer, .enumerationCase].contains(declaration.kind) {
            lines += [
                "        let result: \(planner.qualifiedType(declaration.resultType ?? "Void", owner: declaration.owner)) = \(call)",
            ]
            if !planner.isSendable(
                declaration.resultType ?? "Void",
                relativeTo: declaration.owner,
            ), binding.isMainActor {
                lines
                    .append(
                        "        return try await registry.encodeMainActor(PortholeMainActorValue(result), in: invocation.scope)",
                    )
            } else {
                lines += [
                    "        let reference = try await registry.retain(result, in: invocation.scope, retention: .results)",
                    "        return try .object([\"$reference\": .encoding(reference)])",
                ]
            }
        } else {
            lines += [
                "        let result: \(planner.qualifiedType(declaration.resultType ?? "Void", owner: declaration.owner)) = \(call)",
            ]
            if ["Character", "Substring"].contains(declaration.resultType ?? "Void") {
                lines.append("        return .string(String(result))")
            } else if !planner.isSendable(
                declaration.resultType ?? "Void",
                relativeTo: declaration.owner,
            ), binding.isMainActor {
                lines
                    .append(
                        "        return try await registry.encodeMainActor(PortholeMainActorValue(result), in: invocation.scope)",
                    )
            } else if !planner.isKnownEncodable(
                declaration.resultType ?? "Void",
                relativeTo: declaration.owner,
            ) {
                lines += [
                    "        let reference = try await registry.retain(result, in: invocation.scope, retention: .results)",
                    "        return try .object([\"$reference\": .encoding(reference)])",
                ]
            } else {
                lines
                    .append(
                        "        return try await registry.encode(result, in: invocation.scope)",
                    )
            }
        }
        lines += ["    }"]
        return lines
    }

    private var enumInspectionSchema: String {
        func field(_ name: String, schema: String) -> String {
            "PortholeParameter(name: \(literal(name)), summary: \(literal(name)), schema: \(schema), required: true)"
        }
        let payload = ".object([\([field("name", schema: ".string"), field("label", schema: ".string"), field("type", schema: ".string"), field("value", schema: ".any")].joined(separator: ", "))])"
        return ".object([\(field("case", schema: ".string")), \(field("payloads", schema: ".array(\(payload))"))])"
    }

    /// Switch over the stored enum value. Never invoke an encoder, raw-value getter, or accessor.
    private func enumInspection(_ binding: BindingPlanner.Binding) -> [String] {
        var lines = ["        try Task.checkCancellation()", "        switch receiver {"]
        for enumCase in planner.enumCases(for: binding.declaration) {
            let pattern = enumCase.parameters.enumerated().map { index, payload in
                payload.label == "_" ? "payload\(index)" :
                    "\(payload.label.replacingOccurrences(of: "`", with: "")): payload\(index)"
            }.joined(separator: ", ")
            let target = ".\(escapedIdentifier(enumCase.name))" +
                (enumCase.parameters.isEmpty ? "" : "(\(pattern))")
            var body = ["            case \(enumCase.parameters.isEmpty ? "" : "let ")\(target):"]
            for (index, payload) in enumCase.parameters.enumerated() {
                body += enumPayload(payload, index: index, binding: binding)
            }
            body.append("                try Task.checkCancellation()")
            let payloads = enumCase.parameters.enumerated().map { index, payload in
                ".object([\"name\": .string(\(literal(payload.name))), \"label\": .string(\(literal(payload.label))), \"type\": .string(\(literal(planner.qualifiedType(payload.type, owner: enumCase.owner)))), \"value\": value\(index)])"
            }.joined(separator: ", ")
            body += [
                "                let payloads: [PortholeValue] = [\(payloads)]",
                "                return .object([\"case\": .string(\(literal(enumCase.name))), \"payloads\": .array(payloads)])",
            ]
            lines += conditional(enumCase.conditions, body: body)
        }
        return lines + ["        }"]
    }

    private func enumPayload(
        _ payload: SourceDeclaration.Parameter,
        index: Int,
        binding: BindingPlanner.Binding,
    ) -> [String] {
        let source = "payload\(index)"
        let destination = "value\(index)"
        let type = payload.type.trimmingCharacters(in: .whitespacesAndNewlines)
        let value: String
        switch type {
            case "Void", "()": value = ".null"
            case "Bool": value = ".bool(\(source))"
            case "String": value = ".string(\(source))"
            case "Character", "Substring": value = ".string(String(\(source)))"
            case "Int", "Int8", "Int16", "Int32", "Int64": value = ".integer(Int64(\(source)))"
            case "UInt", "UInt8", "UInt16", "UInt32", "UInt64":
                value = ".unsignedInteger(UInt64(\(source)))"
            case "Float", "Double", "TimeInterval":
                return [
                    "                guard \(source).isFinite else { throw PortholeError.invalidArguments(\(literal("Enum payload '\(payload.name)' is not a finite number."))) }",
                    "                let \(destination): PortholeValue = .number(Double(\(source)))",
                ]
            default:
                if !planner.isSendable(type, relativeTo: binding.declaration.owner),
                   binding.isMainActor
                {
                    return [
                        "                let \(destination) = try await registry.encodeMainActor(PortholeMainActorValue(\(source)), in: invocation.scope)",
                    ]
                }
                return [
                    "                let reference\(index) = try await registry.retain(\(source), in: invocation.scope, retention: .results)",
                    "                let \(destination): PortholeValue = try .object([\"$reference\": .encoding(reference\(index))])",
                ]
        }
        let discard = ["Void", "()"]
            .contains(type) ? ["                let _: Void = \(source)"] : []
        return discard + ["                let \(destination): PortholeValue = \(value)"]
    }

    private func parameterSummary(
        _ parameter: SourceDeclaration.Parameter,
        declaration: SourceDeclaration,
    ) -> String {
        if declaration.kind == .enumerationCase, parameter.label != "_" {
            return "\(parameter.label): \(parameter.type)"
        }
        return parameter.type
    }

    private func usesActorThunk(_ binding: BindingPlanner.Binding) -> Bool {
        binding.isActor && !binding.declaration.isStatic &&
            (binding.declaration.kind == .propertySetter ||
                (binding.declaration.kind == .function && !binding.declaration.isAsync))
    }

    private func nativeArguments(_ declaration: SourceDeclaration) -> String {
        declaration.parameters.enumerated().map { index, parameter in
            parameter.label == "_" ? "value\(index)" : "\(parameter.label.replacingOccurrences(of: "`", with: "")): value\(index)"
        }.joined(separator: ", ")
    }

    private func escapedIdentifier(_ identifier: String) -> String {
        "`\(identifier.replacingOccurrences(of: "`", with: ""))`"
    }

    private func conditional(_ conditions: [String], body: [String]) -> [String] {
        guard !conditions.isEmpty else { return body }
        return ["#if \(conditions.map { "(\($0))" }.joined(separator: " && "))"] + body + ["#endif"]
    }

    private func schema(_ rawType: String) -> String {
        let type = rawType.trimmingCharacters(in: .whitespacesAndNewlines)
        if type.hasSuffix("?") { return ".optional(\(schema(String(type.dropLast()))))" }
        if type.hasPrefix("["), type.hasSuffix("]"), !type.contains(":") {
            return ".array(\(schema(String(type.dropFirst().dropLast()))))"
        }
        if type == "Bool" { return ".boolean" }
        if ["Int", "Int8", "Int16", "Int32", "Int64", "UInt", "UInt8", "UInt16", "UInt32", "UInt64"]
            .contains(type) { return ".integer" }
        if ["Float", "Double", "Decimal", "TimeInterval"].contains(type) { return ".number" }
        if ["String", "Substring", "Character", "URL", "UUID"].contains(type) { return ".string" }
        return ".any"
    }

    private func transferSchema(_ type: String, binding: BindingPlanner.Binding) -> String {
        if binding.isMainActor, !planner.isSendable(type, relativeTo: binding.declaration.owner) {
            // Actor-owned values and containers travel as typed references, not JSON copies.
            return ".any"
        }
        if !["Character", "Substring"].contains(type), !planner.isKnownEncodable(
            type,
            relativeTo: binding.declaration.owner,
        ) {
            // Container codecs do not inherit the explicit scalar Character/Substring codec.
            return ".any"
        }
        return schema(type)
    }

    private func literal(_ value: String) -> String {
        var result = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
                case 34: result += "\\\""
                case 92: result += "\\\\"
                case 10: result += "\\n"
                case 13: result += "\\r"
                case 9: result += "\\t"
                case 0 ... 31: result += "\\u{\(String(scalar.value, radix: 16))}"
                default: result.unicodeScalars.append(scalar)
            }
        }
        return result + "\""
    }
}

/// Retains conditional imports while dropping implementation declarations.
private final class ImportCollector: SyntaxVisitor {
    var declarations: [String] = []

    init() {
        super.init(viewMode: .sourceAccurate)
    }

    override func visit(_ node: ImportDeclSyntax) -> SyntaxVisitorContinueKind {
        // An import in an inactive platform branch must stay in that branch.
        var ancestors: [IfConfigClauseSyntax] = []
        var current = node.parent
        while let ancestor = current {
            if let clause = ancestor.as(IfConfigClauseSyntax.self) { ancestors.append(clause) }
            current = ancestor.parent
        }
        for clause in ancestors.reversed() {
            guard let config = clause.parent?.parent?.as(IfConfigDeclSyntax.self) else { continue }
            for candidate in config.clauses {
                declarations
                    .append(candidate.poundKeyword
                        .text + (candidate.condition.map { " " + $0.trimmedDescription } ?? ""))
                if candidate.id == clause.id { break }
            }
        }
        declarations.append(node.trimmedDescription)
        declarations += ancestors.map { _ in "#endif" }
        return .skipChildren
    }
}
