public enum USState: String, Codable, Sendable, CaseIterable, Hashable {
    case alabama = "AL"
    case alaska = "AK"
    case arizona = "AZ"
    case arkansas = "AR"
    case california = "CA"
    case colorado = "CO"
    case connecticut = "CT"
    case delaware = "DE"
    case florida = "FL"
    case georgia = "GA"
    case hawaii = "HI"
    case idaho = "ID"
    case illinois = "IL"
    case indiana = "IN"
    case iowa = "IA"
    case kansas = "KS"
    case kentucky = "KY"
    case louisiana = "LA"
    case maine = "ME"
    case maryland = "MD"
    case massachusetts = "MA"
    case michigan = "MI"
    case minnesota = "MN"
    case mississippi = "MS"
    case missouri = "MO"
    case montana = "MT"
    case nebraska = "NE"
    case nevada = "NV"
    case newHampshire = "NH"
    case newJersey = "NJ"
    case newMexico = "NM"
    case newYork = "NY"
    case northCarolina = "NC"
    case northDakota = "ND"
    case ohio = "OH"
    case oklahoma = "OK"
    case oregon = "OR"
    case pennsylvania = "PA"
    case rhodeIsland = "RI"
    case southCarolina = "SC"
    case southDakota = "SD"
    case tennessee = "TN"
    case texas = "TX"
    case utah = "UT"
    case vermont = "VT"
    case virginia = "VA"
    case washington = "WA"
    case westVirginia = "WV"
    case wisconsin = "WI"
    case wyoming = "WY"

    public var displayName: String {
        switch self {
            case .alabama: "Alabama"
            case .alaska: "Alaska"
            case .arizona: "Arizona"
            case .arkansas: "Arkansas"
            case .california: "California"
            case .colorado: "Colorado"
            case .connecticut: "Connecticut"
            case .delaware: "Delaware"
            case .florida: "Florida"
            case .georgia: "Georgia"
            case .hawaii: "Hawaii"
            case .idaho: "Idaho"
            case .illinois: "Illinois"
            case .indiana: "Indiana"
            case .iowa: "Iowa"
            case .kansas: "Kansas"
            case .kentucky: "Kentucky"
            case .louisiana: "Louisiana"
            case .maine: "Maine"
            case .maryland: "Maryland"
            case .massachusetts: "Massachusetts"
            case .michigan: "Michigan"
            case .minnesota: "Minnesota"
            case .mississippi: "Mississippi"
            case .missouri: "Missouri"
            case .montana: "Montana"
            case .nebraska: "Nebraska"
            case .nevada: "Nevada"
            case .newHampshire: "New Hampshire"
            case .newJersey: "New Jersey"
            case .newMexico: "New Mexico"
            case .newYork: "New York"
            case .northCarolina: "North Carolina"
            case .northDakota: "North Dakota"
            case .ohio: "Ohio"
            case .oklahoma: "Oklahoma"
            case .oregon: "Oregon"
            case .pennsylvania: "Pennsylvania"
            case .rhodeIsland: "Rhode Island"
            case .southCarolina: "South Carolina"
            case .southDakota: "South Dakota"
            case .tennessee: "Tennessee"
            case .texas: "Texas"
            case .utah: "Utah"
            case .vermont: "Vermont"
            case .virginia: "Virginia"
            case .washington: "Washington"
            case .westVirginia: "West Virginia"
            case .wisconsin: "Wisconsin"
            case .wyoming: "Wyoming"
        }
    }
}
